# -*- mode:python -*-

# Copyright (c) 2006 The Regents of The University of Michigan
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

SimObject('Prefetcher.py', sim_objects=[
    'BasePrefetcher', 'MultiPrefetcher', 'QueuedPrefetcher',
    'StridePrefetcherHashedSetAssociative', 'StridePrefetcher',
    'SmsPrefetcher', 'TaggedPrefetcher', 'IndirectMemoryPrefetcher',
    'SignaturePathPrefetcher', 'SignaturePathPrefetcherV2',
    'AccessMapPatternMatching', 'AMPMPrefetcher',
    'DeltaCorrelatingPredictionTables', 'DCPTPrefetcher',
    'IrregularStreamBufferPrefetcher', 'SlimAMPMPrefetcher',
    'BOPPrefetcher', 'SBOOEPrefetcher', 'STeMSPrefetcher', 'PIFPrefetcher',
    'FetchDirectedPrefetcher'
    ])

Source('access_map_pattern_matching.cc')
Source('base.cc')
Source('multi.cc')
Source('bop.cc')
Source('delta_correlating_prediction_tables.cc')
Source('irregular_stream_buffer.cc')
Source('indirect_memory.cc')
Source('pif.cc')
Source('queued.cc')
Source('sbooe.cc')
Source('sms.cc')
Source('signature_path.cc')
Source('signature_path_v2.cc')
Source('slim_ampm.cc')
Source('spatio_temporal_memory_streaming.cc')
Source('stride.cc')
Source('tagged.cc')
Source('fdp.cc')

GTest('queued.test', 'queued.test.cc', 'queued.cc', 'base.cc',
      '#src/base/logging.cc', '#src/base/hostinfo.cc',
      '#src/base/statistics.cc', '#src/base/stats/info.cc',
      '#src/base/stats/storage.cc', '#src/base/stats/text.cc',
      '#src/base/stats/group.cc', '#src/base/types.cc',
      '#src/base/output.cc', '#src/cpu/reg_class.cc',
      '#src/sim/bufval.cc', '#src/sim/clocked_object.cc',
      '#src/sim/clock_domain.cc', '#src/sim/voltage_domain.cc',
      '#src/sim/sim_object.cc', '#src/sim/drain.cc',
      '#src/mem/cache/replacement_policies/lru_rp.cc',
      '#src/sim/probe/probe.cc', '#src/sim/eventq.cc',
      '#src/sim/async.cc', '#src/mem/packet.cc',
      with_tag('gem5 serialize'), with_tag('gem5 trace'))
